# Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    reviewers:
      - "heridotlife"

  # npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    reviewers:
      - "heridotlife"
    # Group dependency updates
    groups:
      # Group Playwright updates together
      playwright:
        patterns:
          - "@playwright/*"
          - "playwright"
      # Group Tailwind CSS updates together
      tailwind:
        patterns:
          - "@tailwindcss/*"
          - "tailwindcss"
      # Group Alpine.js updates together
      alpinejs:
        patterns:
          - "@alpinejs/*"
          - "alpinejs"
      # Group build tools together
      build-tools:
        patterns:
          - "esbuild"
          - "npm-run-all"
      # Group deployment tools together
      deployment:
        patterns:
          - "wrangler"
          - "http-server"
